SUBSTRATE_VERSION = 1

E_DUPLICATE_MESSAGE_ID = "E_DUPLICATE_MESSAGE_ID"
E_MISSING_PARENT = "E_MISSING_PARENT"
E_PREVIOUS_HASH_MISMATCH = "E_PREVIOUS_HASH_MISMATCH"
E_INVALID_JSON = "E_INVALID_JSON"
E_MISSING_FINAL_NEWLINE = "E_MISSING_FINAL_NEWLINE"
